int amber(int, int);
int test_amber(int, int);
int kaeya();
int test_kaeya();
int dvalin(int);
int dvalin_test(int);
int handbook(int, int);
int test_handbook(int, int);
int medaka(int);
int test_medaka(int);
int sayu(int);
int test_sayu(int);
int kujou(int, int);
int test_kujou(int, int);
int azhdaha(int);
int test_azhdaha(int);
unsigned abyss(unsigned);
unsigned test_abyss(unsigned);
int mondstadt(int);
int test_mondstadt(int);
